[theme]
primaryColor = "#0068c9"                # Класически син бутон
backgroundColor = "#ffffff"             # Бял фон
secondaryBackgroundColor = "#f0f2f6"    # Светлосиви панели
textColor = "#262730"                   # Тъмносив текст
font = "sans serif"
